name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            cd /home/ubuntu

            if [ ! -d APATA ]; then
              git clone https://github.com/sulaimontaoban-lgtm/APATA.git
            fi

            cd APATA

            git fetch origin
            git reset --hard origin/main

            cd my-app

            npm install

            export NODE_OPTIONS="--max-old-space-size=2048"

            npm run build

            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/

            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            sudo systemctl restart nginx